name: camera_streamer
description: A Flutter app that streams camera frames to a server

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  image: ^4.1.3
  http: ^0.13.6

flutter:
  uses-material-design: true
