[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | trim }}{% if commit.author.name %} — @{{ commit.author.name }}{% endif %}
{% endfor %}

{% endfor %}
"""
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
tag_pattern = "v[0-9]*"
split_commits = false

commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^docs", group = "Documentation" },
  { message = "^refact", group = "Refactoring" },

]
